services:
  - type: web
    name: dvary-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: BOT_TOKEN
        value: 8665803785:AAEB0ZUnFH4AiWyd7PtKiwyoGA50-ml0R84
      - key: OWNER_NUMBER
        value: 255XXXXXXXXX
